import '../styles/globals.css'
import { StoreProvider } from "../context/store-context";
import { DisplayProvider } from "../context/display-context";
import type { AppProps } from 'next/app'
import Head from "next/head";
import Layout from "../components/layout/layout";

function MyApp({ Component, pageProps }: AppProps) {
  return (
      <StoreProvider>
        <DisplayProvider>
          <Head>
            <title>Medusa + Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Layout>
            <Component {...pageProps} />
          </Layout>
        </DisplayProvider>
      </StoreProvider>
  )
}

export default MyApp
